import React,{useEffect,useState} from "react";
import {ArrowRight,BarChart3,BookOpen,BrainCircuit,Check,ChevronRight,CircleUserRound,Clock3,Compass,GraduationCap,LayoutDashboard,Lightbulb,Menu,Network,Rocket,ShieldCheck,Sparkles,Star,Target,TrendingUp,X} from "lucide-react";
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid} from "recharts";
import {api} from "./api";

const demo={
 name:"Haripriya",degree:"B.Tech",branch:"CSE / Cybersecurity",college:"MIT-ADT University",
 year:"Third Year",level:"Intermediate",career_goal:"Cybersecurity Analyst",target_salary:"8–12 LPA",
 work_type:"Hybrid",interests:["Cybersecurity","Ethical Hacking","Digital Forensics"],
 skills:[{name:"Python",level:"Intermediate"},{name:"Networking",level:"Intermediate"},
 {name:"Linux",level:"Beginner"},{name:"Cybersecurity",level:"Intermediate"},{name:"C++",level:"Intermediate"}]
};
const fallback=[
 {career:"Cybersecurity Analyst",match:92,description:"Protect systems, investigate incidents and monitor threats.",matched:["Python","Networking","Cybersecurity"],missing:["SIEM","Incident Response"]},
 {career:"Ethical Hacker",match:84,description:"Find and responsibly report vulnerabilities in controlled environments.",matched:["Python","Networking","Cybersecurity"],missing:["Penetration Testing","Web Security"]},
 {career:"Network Engineer",match:79,description:"Design, configure and troubleshoot reliable computer networks.",matched:["Networking","Cybersecurity"],missing:["Cloud Computing","Advanced Linux"]}
];

export default function App(){
 const[profile,setProfile]=useState(demo),[page,setPage]=useState("home"),[recs,setRecs]=useState(fallback),
 [gaps,setGaps]=useState([]),[roadmap,setRoadmap]=useState([]),[resources,setResources]=useState([]),
 [projects,setProjects]=useState([]),[profileId,setProfileId]=useState(null),[done,setDone]=useState({}),
 [loading,setLoading]=useState(false),[sidebar,setSidebar]=useState(false),[toast,setToast]=useState("");

 const analyze=async(p=profile)=>{
  setLoading(true);
  try{
   const[r,g,rm,res,pr]=await Promise.all([api.recommend(p),api.gaps(p),api.roadmap(p),api.resources(),api.projects()]);
   setRecs(r.recommendations);setGaps(g.skills);setRoadmap(rm.roadmap);setResources(res);setProjects(pr);
   const saved=await api.saveProfile(p);setProfileId(saved.id);
  }catch{
   setRecs(fallback);setGaps([{skill:"SIEM",current:0,required:90,gap:90,priority:"High"},{skill:"Incident Response",current:0,required:90,gap:90,priority:"High"},{skill:"Digital Forensics",current:0,required:70,gap:70,priority:"High"},{skill:"Linux",current:40,required:70,gap:30,priority:"Medium"},{skill:"Python",current:70,required:60,gap:0,priority:"Low"}]);
   setRoadmap(localRoadmap());setResources(localResources());setProjects(localProjects());
  }finally{setLoading(false)}
 };
 useEffect(()=>{analyze(demo)},[]);
 const progress=roadmap.length?Math.round(roadmap.filter(x=>done[x.id]).length/roadmap.length*100):0;
 const go=p=>{setPage(p);setSidebar(false);window.scrollTo({top:0,behavior:"smooth"})};
 const generate=async()=>{await analyze(profile);go("dashboard");setToast("Your personalized roadmap is ready.");setTimeout(()=>setToast(""),2500)};
 const toggle=async item=>{const v=!done[item.id];setDone(x=>({...x,[item.id]:v}));try{await api.progress({profile_id:profileId||0,item_id:item.id,completed:v})}catch{}};

 return <div className="shell">
  {page==="home"?<Home onStart={()=>go("profile")} onDemo={()=>{setProfile(demo);generate()}}/>:
  <Layout page={page} go={go} sidebar={sidebar} setSidebar={setSidebar} profile={profile} progress={progress}>
   {page==="profile"&&<Profile profile={profile} setProfile={setProfile} onGenerate={generate}/>}
   {page==="dashboard"&&<Dashboard profile={profile} recs={recs} gaps={gaps} progress={progress} go={go} loading={loading}/>}
   {page==="recommendations"&&<Recommendations recs={recs} setProfile={setProfile} go={go}/>}
   {page==="gaps"&&<Gaps gaps={gaps} career={profile.career_goal}/>}
   {page==="roadmap"&&<Roadmap roadmap={roadmap} done={done} toggle={toggle} progress={progress}/>}
   {page==="resources"&&<Resources resources={resources}/>}
   {page==="projects"&&<Projects projects={projects}/>}
   {page==="feedback"&&<Feedback profileId={profileId}/>}
  </Layout>}
  {toast&&<div className="fixed bottom-5 right-5 z-50 card px-5 py-4 shadow-xl">{toast}</div>}
 </div>
}

function Brand({dark=false}){return <div className="flex items-center gap-3"><div className={`w-9 h-9 rounded-xl flex items-center justify-center ${dark?"bg-sky text-blue":"bg-ink text-white"}`}><Network size={19}/></div><div><div className={`font-semibold tracking-tight ${dark?"text-white":"text-ink"}`}>CareerPath AI</div><div className={`text-[10px] ${dark?"text-slate-400":"text-slate-500"}`}>Your skills. Your goals. Your roadmap.</div></div></div>}

function Home({onStart,onDemo}){
 return <div className="min-h-screen">
  <header className="max-w-7xl mx-auto px-6 py-6 flex items-center justify-between"><Brand/>
   <div className="hidden md:flex items-center gap-7 text-sm text-slate-600"><a href="#how">How it works</a><a href="#features">Features</a><a href="#careers">Careers</a><button onClick={onStart} className="bg-ink text-white px-5 py-2.5 rounded-xl">Get started</button></div>
  </header>
  <main>
   <section className="hero-grid max-w-7xl mx-auto mt-4 mx-6 rounded-[34px] overflow-hidden"><div className="grid lg:grid-cols-[1.05fr_.95fr] gap-12 p-8 md:p-14 lg:p-20 items-center">
    <div><div className="inline-flex items-center gap-2 rounded-full border border-blue/20 bg-white/80 px-4 py-2 text-sm text-blue mb-7"><Sparkles size={16}/> Personalized career guidance</div>
     <h1 className="text-5xl md:text-7xl font-semibold tracking-[-.055em] leading-[.96] text-ink max-w-3xl">Build the career you want, one skill at a time.</h1>
     <p className="mt-7 text-lg md:text-xl leading-8 text-slate-600 max-w-xl">CareerPath AI connects your current skills and interests to a practical learning path — from career choice to projects and certifications.</p>
     <div className="mt-9 flex flex-wrap gap-3"><button onClick={onStart} className="bg-ink text-white px-6 py-3.5 rounded-xl inline-flex items-center gap-2">Generate my roadmap <ArrowRight size={18}/></button><button onClick={onDemo} className="bg-white border border-line px-6 py-3.5 rounded-xl">Try demo profile</button></div>
    </div>
    <div className="relative"><div className="card p-5 shadow-2xl shadow-blue/10 rotate-[1deg]"><div className="flex items-center justify-between border-b border-line pb-4"><div><p className="text-sm text-slate-500">Recommended path</p><h3 className="text-xl font-semibold">Cybersecurity Analyst</h3></div><div className="text-right"><div className="text-3xl font-semibold text-blue">92%</div><p className="text-xs text-slate-500">match</p></div></div>
      <div className="py-5 space-y-5">{[["Your profile","Skills + interests + goal",<CircleUserRound size={18}/>],["Skill gap","SIEM · Incident Response · Forensics",<Target size={18}/>],["Roadmap","6 months · practical milestones",<Rocket size={18}/>]].map(([a,b,I])=><div key={a} className="flex gap-4 items-start"><div className="w-10 h-10 rounded-xl bg-sky flex items-center justify-center text-blue">{I}</div><div><div className="font-medium">{a}</div><div className="text-sm text-slate-500 mt-1">{b}</div></div></div>)}</div>
      <div className="bg-mist rounded-2xl p-4"><div className="flex justify-between text-sm mb-2"><span>Roadmap progress</span><span>42%</span></div><div className="h-2 bg-white rounded-full overflow-hidden"><div className="h-full bg-blue rounded-full w-[42%]"/></div></div>
    </div></div>
   </div></section>
   <section id="how" className="max-w-7xl mx-auto px-6 py-24"><SectionTitle title="From uncertainty to a clear next step." text="The system turns a student's profile into an explainable sequence of career decisions and learning actions."/><div className="grid md:grid-cols-4 gap-4 mt-12">{[["01","Build your profile","Tell us what you know, enjoy and want to achieve.",CircleUserRound],["02","Find your fit","Career paths are ranked using skill and interest matching.",BrainCircuit],["03","See the gap","Understand which skills need attention.",BarChart3],["04","Follow the path","Learn, build projects and track progress.",Rocket]].map(([n,t,d,I])=><div key={n} className="card p-6"><div className="text-sm text-blue mb-10">{n}</div><I size={24}/><h3 className="font-semibold text-xl mt-5">{t}</h3><p className="text-slate-500 mt-2 leading-6">{d}</p></div>)}</div></section>
   <section id="features" className="bg-white border-y border-line"><div className="max-w-7xl mx-auto px-6 py-24"><SectionTitle title="Everything needed to move from a goal to a plan."/><div className="grid md:grid-cols-3 gap-4 mt-12">{[["Career recommendation","See career options with transparent match scores.",Compass],["Skill-gap analysis","Compare current capability with career requirements.",TrendingUp],["Learning roadmap","A sequence of topics, projects and certifications.",BookOpen],["Resources","Connect learning needs to practical resources.",GraduationCap],["Projects","Build portfolio evidence.",Rocket],["Feedback","Rate the roadmap so future versions can improve.",Lightbulb]].map(([t,d,I])=><div className="card card-hover p-6" key={t}><I className="text-blue" size={24}/><h3 className="font-semibold text-lg mt-7">{t}</h3><p className="text-slate-500 mt-2 leading-6">{d}</p></div>)}</div></div></section>
   <section id="careers" className="max-w-7xl mx-auto px-6 py-24"><SectionTitle title="Explore where your skills could take you."/><div className="flex flex-wrap gap-3 mt-9">{["Cybersecurity Analyst","Ethical Hacker","Software Developer","Data Scientist","Machine Learning Engineer","Cloud Engineer","DevOps Engineer","Network Engineer"].map(x=><span key={x} className="px-4 py-2.5 bg-white border border-line rounded-full text-sm">{x}</span>)}</div></section>
  </main>
  <footer className="border-t border-line bg-white"><div className="max-w-7xl mx-auto px-6 py-8 flex justify-between gap-3 text-sm text-slate-500"><span>CareerPath AI · MIT-ADT University</span><span>Your skills. Your goals. Your roadmap.</span></div></footer>
 </div>
}

function Layout({page,go,sidebar,setSidebar,profile,progress,children}){
 const nav=[["dashboard","Overview",LayoutDashboard],["recommendations","Career matches",Compass],["gaps","Skill gap",BarChart3],["roadmap","My roadmap",Rocket],["resources","Resources",BookOpen],["projects","Projects",Lightbulb],["feedback","Feedback",Star]];
 return <div className="min-h-screen flex">
  <aside className={`${sidebar?"translate-x-0":"-translate-x-full"} lg:translate-x-0 fixed z-40 lg:static inset-y-0 left-0 w-72 bg-ink text-white p-6 transition-transform`}><div className="flex items-center justify-between"><Brand dark/><button className="lg:hidden" onClick={()=>setSidebar(false)}><X/></button></div><div className="mt-10 text-xs text-slate-400">YOUR PATH</div><nav className="mt-3 space-y-1">{nav.map(([id,label,I])=><button key={id} onClick={()=>go(id)} className={`w-full flex items-center gap-3 px-3 py-3 rounded-xl text-sm text-left ${page===id?"bg-white/10 text-white":"text-slate-300 hover:bg-white/5"}`}><I size={18}/>{label}</button>)}</nav><div className="mt-10 p-4 rounded-2xl bg-white/5 border border-white/10"><div className="text-sm text-slate-300">Roadmap progress</div><div className="text-2xl font-semibold mt-2">{progress}%</div><div className="h-1.5 bg-white/10 rounded-full mt-3"><div className="h-full bg-sky rounded-full" style={{width:`${progress}%`}}/></div></div></aside>
  {sidebar&&<div className="fixed inset-0 bg-ink/40 z-30 lg:hidden" onClick={()=>setSidebar(false)}/>}
  <main className="flex-1 min-w-0"><header className="h-20 bg-white border-b border-line px-5 md:px-8 flex items-center justify-between sticky top-0 z-20"><button className="lg:hidden" onClick={()=>setSidebar(true)}><Menu/></button><div className="hidden lg:block"><div className="font-semibold">{page==="dashboard"?"Good morning, "+profile.name:titleFor(page)}</div><div className="text-xs text-slate-500 mt-1">CareerPath AI</div></div><div className="ml-auto flex items-center gap-3"><div className="text-right hidden sm:block"><div className="text-sm font-medium">{profile.name}</div><div className="text-xs text-slate-500">{profile.career_goal}</div></div><div className="w-10 h-10 rounded-full bg-sky flex items-center justify-center font-semibold text-blue">{profile.name?.[0]||"U"}</div></div></header><div className="max-w-7xl mx-auto p-5 md:p-8">{children}</div></main>
 </div>
}
function titleFor(p){return {recommendations:"Career matches",gaps:"Skill gap analysis",roadmap:"My learning roadmap",resources:"Learning resources",projects:"Portfolio projects",feedback:"Roadmap feedback",profile:"Build your profile"}[p]||"CareerPath AI"}
function SectionTitle({title,text}){return <div className="max-w-2xl"><h2 className="text-3xl md:text-5xl font-semibold tracking-[-.04em] leading-tight">{title}</h2>{text&&<p className="text-slate-500 text-lg leading-7 mt-4">{text}</p>}</div>}

function Profile({profile,setProfile,onGenerate}){
 const names=["Python","Java","C++","JavaScript","SQL","Cybersecurity","Networking","Linux","Cloud Computing","Machine Learning","Data Analysis","Problem Solving"];
 const update=(k,v)=>setProfile({...profile,[k]:v});
 const toggle=s=>setProfile(p=>({...p,skills:p.skills.some(x=>x.name===s)?p.skills.filter(x=>x.name!==s):[...p.skills,{name:s,level:"Intermediate"}]}));
 return <div className="space-y-7"><div><h1 className="text-3xl md:text-4xl font-semibold">Build your profile</h1><p className="text-slate-500 mt-2">Give CareerPath AI enough context to make the recommendation useful.</p></div><div className="card p-6 md:p-8 space-y-8"><div className="grid md:grid-cols-2 gap-5">
  {[["Name","name"],["Degree","degree"],["Branch","branch"],["College","college"],["Career goal","career_goal"],["Target salary","target_salary"]].map(([l,k])=><label key={k} className="block"><span className="text-sm font-medium">{l}</span><input value={profile[k]||""} onChange={e=>update(k,e.target.value)} className="w-full border border-line rounded-xl px-4 py-3 mt-2 bg-white"/></label>)}
  <label><span className="text-sm font-medium">Current year</span><select value={profile.year} onChange={e=>update("year",e.target.value)} className="w-full border border-line rounded-xl px-4 py-3 mt-2"><option>First Year</option><option>Second Year</option><option>Third Year</option><option>Final Year</option></select></label>
  <label><span className="text-sm font-medium">Current level</span><select value={profile.level} onChange={e=>update("level",e.target.value)} className="w-full border border-line rounded-xl px-4 py-3 mt-2"><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label>
 </div><div><h3 className="font-semibold text-lg">Skills</h3><p className="text-sm text-slate-500 mt-1">Select skills you already have.</p><div className="flex flex-wrap gap-2 mt-4">{names.map(s=><button key={s} onClick={()=>toggle(s)} className={`px-3.5 py-2 rounded-full border text-sm ${profile.skills.some(x=>x.name===s)?"bg-ink text-white border-ink":"bg-white border-line text-slate-600"}`}>{s}</button>)}</div></div><div className="flex justify-end"><button onClick={onGenerate} className="bg-ink text-white px-6 py-3 rounded-xl flex items-center gap-2">Generate my roadmap <ArrowRight size={17}/></button></div></div></div>
}

function Stat({title,value,icon:I}){return <div className="card p-5 flex items-center gap-4"><div className="w-11 h-11 rounded-xl bg-sky text-blue flex items-center justify-center"><I size={20}/></div><div><div className="text-2xl font-semibold">{value}</div><div className="text-sm text-slate-500">{title}</div></div></div>}

function Dashboard({profile,recs,gaps,progress,go,loading}){
 const top=recs[0]||fallback[0]; const chart=gaps.slice(0,6).map(x=>({name:x.skill,Current:x.current,Required:x.required}));
 return <div className="space-y-7"><div className="grid xl:grid-cols-[1.4fr_.6fr] gap-5"><div className="card bg-ink text-white p-7 md:p-9 relative overflow-hidden"><div className="relative z-10"><div className="text-slate-300 text-sm">Your recommended direction</div><h1 className="text-4xl md:text-5xl font-semibold mt-3">{top.career}</h1><p className="text-slate-300 mt-4 max-w-xl leading-7">{top.description}</p><button onClick={()=>go("roadmap")} className="mt-7 bg-white text-ink px-5 py-3 rounded-xl inline-flex items-center gap-2">Open roadmap <ArrowRight size={17}/></button></div><div className="absolute right-8 top-8 text-7xl font-semibold text-white/10">{top.match}%</div></div><div className="card p-7"><div className="text-sm text-slate-500">Career match</div><div className="text-6xl font-semibold mt-3 text-blue">{top.match}%</div><p className="text-slate-500 mt-2">Based on skills, interests and goal.</p><button onClick={()=>go("recommendations")} className="mt-6 text-sm font-medium flex items-center gap-2">See other matches <ChevronRight size={16}/></button></div></div>
 <div className="grid md:grid-cols-3 gap-5"><Stat title="Roadmap progress" value={`${progress}%`} icon={Rocket}/><Stat title="Priority skills" value={gaps.filter(x=>x.gap>20).length} icon={Target}/><Stat title="Learning path" value="6 months" icon={Clock3}/></div>
 <div className="grid xl:grid-cols-[1.2fr_.8fr] gap-5"><div className="card p-6"><div className="flex justify-between items-end"><div><h2 className="font-semibold text-xl">Skill readiness</h2><p className="text-sm text-slate-500 mt-1">Current capability versus requirement.</p></div><button onClick={()=>go("gaps")} className="text-sm text-blue">Full analysis</button></div><div className="h-72 mt-5">{loading?<div className="h-full flex items-center justify-center text-slate-500">Analyzing your profile…</div>:<ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E5EDF5"/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis domain={[0,100]}/><Tooltip/><Bar dataKey="Current" fill="#2F73C9" radius={[5,5,0,0]}/><Bar dataKey="Required" fill="#C9D9E8" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer>}</div></div>
 <div className="card p-6"><h2 className="font-semibold text-xl">Next best actions</h2><div className="mt-5 space-y-4">{gaps.filter(x=>x.gap>20).slice(0,3).map(x=><div key={x.skill} className="border-b border-line pb-4"><div className="flex justify-between"><span className="font-medium">{x.skill}</span><span className="text-xs text-blue">{x.priority} priority</span></div><p className="text-sm text-slate-500 mt-1">Close a {x.gap}-point gap through focused practice.</p></div>)}</div><button onClick={()=>go("roadmap")} className="mt-5 w-full border border-line rounded-xl py-3 text-sm">See learning sequence</button></div></div></div>
}

function Recommendations({recs,setProfile,go}){return <div className="space-y-7"><div><h1 className="text-3xl font-semibold">Career matches</h1><p className="text-slate-500 mt-2">Ranked from your skills, interests and goal.</p></div><div className="grid gap-4">{recs.map(r=><div key={r.career} className="card p-6 flex flex-col md:flex-row md:items-center gap-6"><div className="w-14 h-14 rounded-2xl bg-sky flex items-center justify-center text-blue"><ShieldCheck/></div><div className="flex-1"><div className="flex flex-wrap gap-3 items-center"><h2 className="text-xl font-semibold">{r.career}</h2><span className="px-2.5 py-1 rounded-full bg-sky text-blue text-sm font-medium">{r.match}% match</span></div><p className="text-slate-500 mt-2">{r.description}</p><div className="flex flex-wrap gap-2 mt-4">{r.matched?.map(x=><span className="text-xs bg-mist px-2.5 py-1.5 rounded-full" key={x}>✓ {x}</span>)}</div><div className="text-sm text-slate-500 mt-3">Build next: {r.missing?.join(" · ")}</div></div><button onClick={()=>{setProfile(p=>({...p,career_goal:r.career}));go("gaps")}} className="border border-line px-5 py-3 rounded-xl whitespace-nowrap">Analyze path</button></div>)}</div></div>}

function Gaps({gaps,career}){return <div className="space-y-7"><div><h1 className="text-3xl font-semibold">Skill gap analysis</h1><p className="text-slate-500 mt-2">Target: {career}</p></div><div className="card p-6"><div className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={gaps} layout="vertical" margin={{left:20,right:20}}><CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#E5EDF5"/><XAxis type="number" domain={[0,100]}/><YAxis dataKey="skill" type="category" width={125} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="current" fill="#2F73C9" name="Current" radius={[0,5,5,0]}/><Bar dataKey="required" fill="#C9D9E8" name="Required" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></div></div><div className="grid md:grid-cols-3 gap-4">{gaps.filter(x=>x.gap>20).slice(0,3).map(x=><div className="card p-5" key={x.skill}><div className="text-xs text-blue">{x.priority} priority</div><h3 className="font-semibold mt-2">{x.skill}</h3><p className="text-sm text-slate-500 mt-2">Current {x.current}% · Required {x.required}%</p><div className="h-1.5 bg-mist rounded-full mt-4"><div className="h-full bg-blue rounded-full" style={{width:`${x.current}%`}}/></div></div>)}</div></div>}

function Roadmap({roadmap,done,toggle,progress}){const months=[...new Set(roadmap.map(x=>x.month))];return <div className="space-y-7"><div className="flex justify-between items-end"><div><h1 className="text-3xl font-semibold">My learning roadmap</h1><p className="text-slate-500 mt-2">A practical sequence from fundamentals to career preparation.</p></div><div className="text-right"><div className="text-3xl font-semibold text-blue">{progress}%</div><div className="text-xs text-slate-500">complete</div></div></div><div className="card p-6 md:p-8">{months.map((m,i)=><div key={m} className="relative pl-12 pb-10 last:pb-0"><div className="absolute left-0 top-0 w-9 h-9 rounded-full bg-sky text-blue flex items-center justify-center text-xs font-semibold">{i+1}</div>{i<months.length-1&&<div className="timeline-line"/>}<div className="flex items-center gap-3"><h2 className="text-xl font-semibold">{m}</h2><span className="text-xs bg-mist px-2.5 py-1 rounded-full text-slate-500">{roadmap.find(x=>x.month===m)?.phase}</span></div><div className="grid md:grid-cols-2 gap-3 mt-4">{roadmap.filter(x=>x.month===m).map(item=><button key={item.id} onClick={()=>toggle(item)} className={`text-left border rounded-2xl p-4 ${done[item.id]?"border-blue/30 bg-sky/40":"border-line bg-white"}`}><div className="flex gap-3"><div className={`w-6 h-6 rounded-full border flex items-center justify-center shrink-0 ${done[item.id]?"bg-blue border-blue text-white":"border-line"}`}>{done[item.id]&&<Check size={14}/>}</div><div><div className={`font-medium ${done[item.id]?"line-through text-slate-500":""}`}>{item.title}</div><div className="text-sm text-slate-500 mt-1">{item.description}</div><div className="text-xs text-slate-400 mt-3">{item.difficulty} · {item.hours} hours</div></div></div></button>)}</div></div>)}</div></div>}

function Resources({resources}){return <div className="space-y-7"><div><h1 className="text-3xl font-semibold">Learning resources</h1><p className="text-slate-500 mt-2">Places to turn roadmap topics into practice.</p></div><div className="grid md:grid-cols-2 gap-4">{resources.map(r=><div className="card card-hover p-6" key={r.title}><div className="flex justify-between"><div><div className="text-xs text-blue">{r.type}</div><h3 className="font-semibold text-lg mt-2">{r.title}</h3></div><BookOpen className="text-slate-300"/></div><div className="mt-5 text-sm text-slate-500 flex gap-4"><span>{r.platform}</span><span>{r.duration}</span></div><div className="mt-4 inline-block text-xs bg-mist px-2.5 py-1.5 rounded-full">{r.skill}</div></div>)}</div></div>}

function Projects({projects}){return <div className="space-y-7"><div><h1 className="text-3xl font-semibold">Portfolio projects</h1><p className="text-slate-500 mt-2">Build evidence of your skills while following the roadmap.</p></div><div className="grid md:grid-cols-2 gap-4">{projects.map(p=><div className="card p-6" key={p.title}><div className="flex justify-between"><span className="text-xs bg-sky text-blue px-2.5 py-1.5 rounded-full">{p.difficulty}</span><span className="text-xs text-slate-400">{p.hours} hours</span></div><h3 className="font-semibold text-xl mt-5">{p.title}</h3><p className="text-slate-500 mt-2 leading-6">{p.description}</p><div className="flex gap-2 mt-5 flex-wrap">{p.skills.map(s=><span key={s} className="text-xs bg-mist px-2.5 py-1.5 rounded-full">{s}</span>)}</div></div>)}</div></div>}

function Feedback({profileId}){const[rating,setRating]=useState(5),[comment,setComment]=useState(""),[sent,setSent]=useState(false);const submit=async()=>{try{await api.feedback({profile_id:profileId,rating,relevance:rating,usefulness:rating,achievability:rating,comment})}catch{}setSent(true)};return <div className="max-w-2xl space-y-7"><div><h1 className="text-3xl font-semibold">How useful was your roadmap?</h1><p className="text-slate-500 mt-2">Your feedback is part of the product loop.</p></div><div className="card p-7">{sent?<div className="text-center py-12"><div className="w-14 h-14 rounded-full bg-sky text-blue flex items-center justify-center mx-auto"><Check/></div><h2 className="font-semibold text-2xl mt-5">Thanks for the feedback.</h2><p className="text-slate-500 mt-2">It has been recorded for this demo.</p></div>:<><div className="flex gap-2">{[1,2,3,4,5].map(x=><button key={x} onClick={()=>setRating(x)} className={x<=rating?"text-blue":"text-slate-300"}><Star fill="currentColor" size={32}/></button>)}</div><p className="mt-5 font-medium">What would you improve?</p><textarea value={comment} onChange={e=>setComment(e.target.value)} className="w-full border border-line rounded-xl p-4 mt-3 h-32" placeholder="Tell us what felt useful or missing."/><button onClick={submit} className="mt-4 bg-ink text-white px-5 py-3 rounded-xl">Save feedback</button></>}</div></div>}

function localRoadmap(){return ["Linux Basics","Networking Fundamentals","Python for Security","Security Fundamentals","OWASP Basics","SIEM Fundamentals","Wireshark","Vulnerability Assessment","Network Scanner","Log Analysis Dashboard","Security+ Preparation","GitHub Portfolio"].map((x,i)=>({id:`r${i+1}`,month:`Month ${Math.min(6,Math.floor(i/2)+1)}`,phase:i<3?"Foundation":i<6?"Core Skills":i<8?"Practical Skills":i<10?"Projects":"Career Preparation",title:x,description:`Build practical ability in ${x.toLowerCase()}.`,difficulty:i<3?"Beginner":"Intermediate",hours:8+i%4*3}))}
function localResources(){return [{title:"Linux Fundamentals",platform:"Cisco Networking Academy",type:"Free",skill:"Linux",duration:"20 hours"},{title:"Introduction to Cybersecurity",platform:"Cisco Networking Academy",type:"Free",skill:"Cybersecurity",duration:"15 hours"},{title:"Web Security Academy",platform:"PortSwigger",type:"Free",skill:"Web Security",duration:"Self-paced"}]}
function localProjects(){return [{title:"Password Strength Analyzer",difficulty:"Beginner",hours:6,skills:["Python","Security"],description:"Build a local educational tool for evaluating password strength."},{title:"Network Scanner",difficulty:"Intermediate",hours:12,skills:["Python","Networking"],description:"Create a controlled local-network scanner for learning."}]}
